export const UPDATE_UNICORN_DIRECTORY = 'UPDATE_UNICORN_DIRECTORY'
export const UPDATE_OPEN_DIRECTORY = 'UPDATE_OPEN_DIRECTORY'
export const UPDATE_DIRECTORY_FILE_STATUS = 'UPDATE_DIRECTORY_FILE_STATUS'